  <div id="footer">
    <div id="footer_contents">
      <div id="footer_title" class="cb">
        <p class="foot_copy"><span>お気軽にご相談ください</span>食生活アドバイザー<sup>&#174;</sup></p>
        <p class="tel_btn" x-ms-format-detection="none"><span class="tel_ttl">検定事務局</span><img src="/img/foot_tel.gif" width="29" height="29" alt="tel" />0120-86-3593<br />
        <span class="tel_ttl">Academy事務局</span><img src="/img/foot_tel.gif" width="29" height="29" alt="tel" />0120-20-9039
        <span>受付時間 平日10:00~16:00</span></p>
          <p id="privacy_mark"><a href="https://privacymark.jp/" target="_blank"><img src="/privacy/img/pmarklogo.gif" width="57" height="61"></a></p>
          </div>
      <div id="booter_link" class="cb">
        <dl>
          <dt><a href="/">トップページ</a></dt>
          <dt>食生活アドバイザー<sup>&#174;</sup>とは</dt>
          <dd><a href="/ado/">食生活アドバイザー<sup>&#174;</sup> ってどんな資格？</a></dd>
          <dd><a href="/ado/field.html">活躍のフィールド</a></dd>
          <dd><a href="/ado/fukugo.html">プラスα複合資格</a></dd>
          <dt>受験案内</dt>
          <dd><a href="/juken/kentei.html">食生活アドバイザー<sup>&#174;</sup> 検定とは</a></dd>
          <dd><a href="/juken/">試験概要</a></dd>
          <dd><a href="/juken/kouza.html">合格講座概要</a>
            <ul>
              <li><a href="/juken/kouza3.html">3級カリキュラム</a></li>
              <li><a href="/juken/kouza2.html">2級カリキュラム</a></li>
            </ul>
            </dd>
          <dd><a href="/juken/mogi3.html">チャレンジ問題</a>
            <ul>
              <li><a href="/juken/mogi3.html">チャレンジ問題3級</a></li>
              <li><a href="/juken/mogi2.html">チャレンジ問題2級</a></li>
            </ul>
          </dd>
          <dd><a href="/juken/mohan.html">検定試験模範解答</a></dd>
          <dd><a href="/shoseki/">書籍紹介</a>
            <ul>
              <li><a href="/shoseki/">書籍紹介</a></li>
              <li><a href="/shoseki/past.html">過去問題集</a></li>
            </ul>
         </dd>
          <dd class="btm_border"><a href="/qa/">Q&amp;A（よくある質問）</a></dd>
        </dl>
        <dl>
          <dt>願書請求 </dt>
          <dd><a href="/gansho/">願書請求の流れ</a></dd>
<!--フォーム-->
<!--
          <dd><a href="https://ssl.flanet.jp/ganshoform/" target="_blank">願書請求フォーム</a></dd>
          <dd><a href="https://ssl.flanet.jp/memberform/" target="_blank">登録情報の変更フォーム</a></dd>
-->
<!--フォームここまで-->

          <dt><a href="/tusin/">通信講座</a></dt>
          <dd><a href="https://www.hj.sanno.ac.jp/cp/distance-learning/search/?kw=%E9%A3%9F%E7%94%9F%E6%B4%BB%E3%82%A2%E3%83%89%E3%83%90%E3%82%A4%E3%82%B6%E3%83%BC" target="_blank">産業能率大学　総合研究所</a></dd>
          <dd>ユーキャン
      <ul><li><a href="http://www.u-can.co.jp/course/data/in_html/1327/" target="_blank">食生活アドバイザー<sup>&#174;</sup>合格講座</a></li>
          <li><a href="http://www.u-can.co.jp/course/data/in_html/1400/" target="_blank">野菜スペシャリスト<sup>&#174;</sup>講座</a><li></ul></dd>
          <dd><a href="https://www.jmam.co.jp/tsukyocatalog/category.html" target="_blank">日本能率協会マネジメントセンター</a></dd>

          <dt>受験（資格関連情報）</dt>
          <dd><a href="/dantai/">団体受験</a>
          <dd><a href="/gokaku/">合格者インタビュー </a>　　
            <ul>
              <li><a href="/gokaku/">松尾 喜代江さん</a></li>
              <li><a href="/gokaku/index2.html">&#39641;崎 智士さん</a></li>
            </ul>
          </dd>
          <dd><a href="/kaiin/">食アド<sub>&#174;</sub> 会員制度</a></dd>
<!--
          <dt>日本の資格検定</dt>
          <dd class="btm_border"><a href="https://jpsk.jp/article/award2019.html" target="_blank">「日本の資格・検定」AWARDS 2019</a></dd>
-->
        </dl>
        <dl class="no_dl">
          <dt><a href="kyokai/">協会情報</a></dt>
          <dd><a href="/kyokai/">会長のごあいさつ</a></dd>
          <dd><a href="/kyokai/index2.html">FLAネットワーク協会とは</a></dd>
          <dt>OTHERS</dt>
          <dd><a href="/info/">お問い合せ</a></dd>
          <dd><a href="/link/">リンク集</a></dd>
          <dd><a href="/sitemap/">サイトマップ</a></dd>

          <dt>食生活アドバイザー<sup>&#174;</sup> のための健康レシピ</dt>
					<dd><a href="/recipe/">レシピ一覧</a></dd>

          <dt>月刊コラム 食生活マメ知識</dt>
          <dd><a href="/column/">更新月順一覧</a></dd>
          <dd><a href="/column/index2.html">カテゴリ別一覧</a></dd>

          <dt>食アド<sub>&#174;</sub> &  野スぺ<sub>&#174;</sub></dt>
					<dd><a href="/event/">月間ニューステーブル</a></dd>

          <dt><a href="/privacy/index2.html">Pマーク</a></dt>
          <dd><a href="/privacy/index2.html">個人情報保護方針</a></dd>
          <dd class="btm_border"><a href="/privacy/index3.html">個人情報の利用目的の公表、<br />及び開示等に応じる手続き</a></dd>
        </dl>
      </div>

    </div>
    <p id="footer_copy">Copyright(C) 2019 FLAネットワーク協会 All Rights Reserved</p>
  </div>
  <p id="pagetop"><a href="#page_top"><img src="/img/page_top.gif" width="56" height="56" alt="ページの先頭へ" class="btnover" /></a></p>  
