
      <!--side_banner start -->
      <ul id="side_banner">
<!--フォーム->
        <li id="side_banner01"><a href="https://ssl.flanet.jp/ganshoform/" target="_blank"><img src="/img/side_banner01.gif" alt="願書応募フォームはこちら" class="btnover" /></a></li>
        <li id="side_banner02"><a href="https://ssl.flanet.jp/memberform/" target="_blank"><img src="/img/side_banner02.gif" alt="情報の変更はこちら" class="btnover" /></a></li>
-->
        <li id="side_banner03"><a href="http://www.u-can.co.jp/course/data/in_html/1327/" target="_blank"><img src="/img/side_banner03.gif" alt="ユーキャンの食生活アドバイザー（2級・3級）" class="btnover" /></a></li>
				<li id="side_banner08"><a href="http://www.u-can.co.jp/course/data/in_html/1400/" target="_blank"><img src="/img/side_banner15.gif" alt="ユーキャンの野菜スペシャリスト講座" class="btnover" /></a></li>
				<li id="side_banner19"><a href="http://manatopi.u-can.co.jp/kichisemichiko/index.html" target="_blank"><img src="/img/side_banner17.gif" alt="ユーキャンのマナトピ" class="btnover" /></a></li>
				<li id="side_banner17"><a href="http://www.hj.sanno.ac.jp/ps/course/list/3969" target="_blank"><img src="/img/side_banner16.gif" alt="産能大通信講座" class="btnover" /></a></li>
        <li id="side_banner04"><a href="/juken/"><img src="/img/side_banner04.gif" alt="受験概要はこちら 受験案内" class="btnover" /></a></li>
        <li id="side_banner05"><a href="/gansho/"><img src="/img/side_banner05.gif" alt="受験までの流れをチェック 願書請求について" class="btnover" /></a></li>
        <li id="side_banner06"><a href="/juken/mogi3.html"><img src="/img/side_banner06.gif" alt="自分のレベルをチェック 模擬問題" class="btnover" /></a></li>
        <li id="side_banner07"><a href="/juken/kouza.html"><img src="/img/side_banner07.gif" alt="合格を目指して集中的に学習しよう 合格講座" class="btnover" /></a></li>
        <li class="m_b25" id="dantai_banner"><a href="/dantai/"><img src="/img/side_banner08.gif" alt="団体受験をご検討の方へ" class="btnover" /></a></li>
        <li id="side_banner18" class="m_b10"><a href="/gokaku/"><img src="/img/side_banner11.jpg" alt="合格者インタビュー 　松尾喜代江さん" class="btnover" /></a></li>
        <li id="side_banner09" class="m_b25"><a href="/gokaku/index2.html"><img src="/img/side_banner12.jpg" alt="合格者インタビュー 　高崎智士さん" class="btnover" /></a></li>
        <li class="m_b10" id="syoseki_banner">
        <p class="m_b10"><a href="/shoseki/"><img src="/img/side_banner09.gif" alt="書籍紹介" class="btnover" /></a></p>
        <p><a href="/kaiin/"><img src="/img/side_banner10.gif" alt="食アド会員制度" class="btnover" /></a></p>
        </li>
        <li class="m_b10" id="koramu_banner">
        <p class="m_b10"><a href="/column/"><img src="/img/side_banner13.gif" alt="月刊コラム 食生活マメ知識" class="btnover" /></a></p>
        <p id="side_health_recipes"><a href="/recipe/"><img src="/img/side_banner14.gif" alt="食生活アドバイザー&#174;のための健康レシピ" class="btnover" /></a></p>
        </li>
      </ul>
      <!--side_banner end --> 
      
      <!--top_bottom_link start -->
      <ul id="top_bottom_link" class="cb">
        <li id="top_kyokai"><a href="/kyokai/">協会情報</a></li>
        <li id="top_tusin"><a href="/tusin/">通信講座</a></li>
        <li id="top_link"><a href="/link/">リンク集</a></li>
      </ul>
      <!--top_bottom_link end --> 