  <div id="footer">
    <div id="footer_contents">
      <div id="footer_title" class="cb">
        <p class="fl">お気軽にご相談ください　食生活アドバイザー<sup>&#174;</sup> 検定事務局</p>
        <p class="tel_btn fr"><img src="/img/footer_tel.gif" width="296" height="30" alt="0120-86-3593" /></p>
      </div>
      <div id="booter_link" class="cb">
        <dl>
          <dt><a href="/">トップページ</a></dt>
          <dt>食生活アドバイザー<sup>&#174;</sup>とは</dt>
          <dd><a href="/ado/">食生活アドバイザー<sup>&#174;</sup> ってどんな資格？</a></dd>
          <dd><a href="/ado/field.html">活躍のフィールド</a></dd>
          <dd><a href="/ado/fukugo.html">プラスα複合資格</a></dd>
          <dt>受験案内</dt>
          <dd><a href="/juken/kentei.html">食生活アドバイザー<sup>&#174;</sup> 検定とは</a></dd>
          <dd><a href="/juken/">試験概要</a></dd>
          <dd><a href="/juken/kouza.html">合格講座概要</a>
            <ul>
              <li><a href="/juken/kouza3.html">3級カリキュラム</a></li>
              <li><a href="/juken/kouza2.html">2級カリキュラム</a></li>
            </ul>
            </dd>
          <dd><a href="/juken/mogi3.html">模擬問題</a>
            <ul>
              <li><a href="/juken/mogi3.html">模擬問題3級</a></li>
              <li><a href="/juken/mogi2.html">模擬問題2級</a></li>
            </ul>
          </dd>
          <dd><a href="/juken/mohan.html">試験問題模範解答</a></dd>
          <dd><a href="/shoseki/">書籍紹介</a></dd>
          <dd><a href="/qa/">Q&amp;A（よくある質問）</a></dd>
        </dl>
        <dl>
          <dt>願書請求 　
          <dd><a href="/gansho/">願書請求の流れ</a></dd>
<!--フォーム->
          <dd><a href="https://ssl.flanet.jp/ganshoform/" target="_blank">願書請求フォーム</a></dd>
          <dd><a href="https://ssl.flanet.jp/memberform/" target="_blank">登録情報の変更フォーム</a></dd>
-->
          <dt><a href="/tusin/">通信講座</a></dt>
          <dd>ユーキャン
      <ul><li><a href="http://www.u-can.co.jp/course/data/in_html/1327/" target="_blank">食生活アドバイザー<sup>&#174;</sup>合格講座</a></li>
          <li><a href="http://www.u-can.co.jp/course/data/in_html/1400/" target="_blank">野菜スペシャリスト講座</a><li></ul></dd>
          <dd><a href="http://www.hj.sanno.ac.jp/ps/course/list/3969" target="_blank">産業能率大学　総合研究所</a></dd>
          <dt>受験（資格関連情報）</dt>
          <dd><a href="/event/">食アド＆野スペ<br>　『月刊ニューステーブル』</a>
          <dd><a href="/dantai/">団体受験</a>
          <dd><a href="/gokaku/">合格者インタビュー </a>　　
            <ul>
              <li><a href="/gokaku/">松尾 喜代江さん</a></li>
              <li><a href="/gokaku/index2.html">&#39641;崎 智士さん</a></li>
            </ul>
          </dd>
          <dd><a href="/kaiin/">食アド<sub>&#174;</sub> 会員制度</a></dd>
        </dl>
        <dl class="no_dl">
          <dt><a href="kyokai/">協会情報</a></dt>
          <dd><a href="/kyokai/">会長のごあいさつ</a></dd>
          <dd><a href="/kyokai/index2.html">FLAネットワーク協会とは</a></dd>
          <dt>OTHERS</dt>
          <dd><a href="/info/">お問い合せ</a></dd>
          <dd><a href="/link/">リンク集</a></dd>
          <dd><a href="/sitemap/">サイトマップ</a></dd>
          <dt><a href="/recipe/">食生活アドバイザー<sup>&#174;</sup> のための健康レシピ<br />
            レシピ一覧</a></dt>
          <dt><a href="/column/">月刊コラム 食生活マメ知識</a></dt>
          <dd><a href="/column/">更新月順一覧</a></dd>
          <dd><a href="/column/index2.html">カテゴリ別一覧</a></dd>
          <dt><a href="/privacy/index2.html">Pマーク</a></dt>
          <dd><a href="/privacy/index2.html">個人情報保護方針</a></dd>
          <dd><a href="/privacy/index3.html">個人情報の利用目的の公表、<br />及び開示等に応じる手続き</a></dd>
        </dl>
      </div>
          <p id="privacy_mark"><a href="https://privacymark.jp/" target="_blank"><img src="/privacy/img/pmarklogo.gif" width="81" height="87"></a></p>
    </div>
    <p id="footer_copy">Copyright(C) 2016 FLAネットワーク協会 All Rights Reserved</p>
  </div>
  <p id="pagetop"><a href="#page_top"><img src="/img/page_top.gif" width="56" height="56" alt="ページの先頭へ" class="btnover" /></a></p>