






  <div id="footer">
    <div id="footer_contents">
      <div id="footer_title" class="cb">
        <p class="foot_copy"><span>お気軽にご相談ください</span>食生活アドバイザー®</p>
        <p class="tel_btn" x-ms-format-detection="none"><span class="tel_ttl">検定事務局</span><img src="/img/foot_tel.gif" width="29" height="29" alt="tel" />0120-86-3593<br />
        <span class="tel_ttl">Academy事務局</span><img src="/img/foot_tel.gif" width="29" height="29" alt="tel" />0120-20-9039
        <span>受付時間 平日10:00~16:00</span></p>
      </div>
      
      <div id="booter_link" class="cb">
        <dl>
          <dt><a href="/">トップページ</a></dt>

          <dt><a href="/ado/">食生活アドバイザー®とは</a></dt>

          <dt><a href="/juken/">個人受験</a></dt>
          <dd><a href="/pdf/20251125_preparation.pdf">3・2級郵便局、ゆうちょ銀行申込</a></dd>
          <dd><a href="/pdf/20251125_preparation.pdf">3級・2級クレジットカード申込</a></dd>
          <dd><a href="/pdf/20251125_preparation.pdf">1級郵便局、ゆうちょ銀行申込</a></dd>
          <dd><a href="/pdf/20251125_preparation.pdf">1級クレジットカード申込</a></dd>

          <dt><a href="/pass/">合格講座</a></dt>

          <dt><a href="/shoseki/">書籍紹介</a></dt>

          <dt><a href="/dantai/">団体受験</a></dt>

          <dt class="btm_border"><a href="https://shoku-ad.jp/member/" target="_blanck">食アド<sub>®</sub> 会員制度</a></dt>

        </dl>

<!--中央ブロック-->
        <dl>

<!--団体受験-->
          <dt>食生活アドバイザー® のための健康レシピ</dt>
					<dd><a href="/recipe/">レシピ一覧</a></dd>

          <dt>食アド<sub>®</sub> &  野スぺ<sub>®</sub></dt>
					<dd><a href="https://shoku-ad.jp/club2022/newstable/">月刊ニューステーブル</a></dd>
          <dt><a href="/privacy/index2.html">個人情報</a></dt>
          <dd><a href="/privacy/index2.html">個人情報保護方針</a></dd>

          <dt><a href="https://flanet.jp/torihikihou/index.html">特定商取引に基づく表記</a></dt>

          <dt><a href="/kyokai/">協会情報</a></dt>
          <dd><a href="/kyokai/">会長のごあいさつ</a></dd>
          <dd class="btm_border"><a href="/kyokai/index2.html">FLAネットワーク®協会とは</a></dd>

        </dl>

<!--右ブロック-->
        <dl class="no_dl">

          <dt><a href="/tusin/">通信講座</a></dt>
          <dd><a href="https://www.hj.sanno.ac.jp/cp/distance-learning/search/?kw=%E9%A3%9F%E7%94%9F%E6%B4%BB%E3%82%A2%E3%83%89%E3%83%90%E3%82%A4%E3%82%B6%E3%83%BC" target="_blank">産業能率大学　総合研究所</a></dd>
          <dd>
            <a href="https://www.u-can.co.jp/course/data/in_html/1327/" target="_blank">ユーキャン</a>
          </dd>
          <dd><a href="https://www.jmam.co.jp/tsukyocatalog/category.html" target="_blank">日本能率協会マネジメントセンター</a></dd>

          <dt>OTHERS</dt>
          <dd><a href="/info/">お問い合せ</a></dd>
          <dd><a href="/link/">リンク集</a></dd>
          <dd class="btm_border"><a href="/sitemap/">サイトマップ</a></dd>

        </dl>
      </div>

    </div>
    <p id="footer_copy">Copyright(C) 2019 FLAネットワーク®協会 All Rights Reserved</p>
  </div>
  <p id="pagetop"><a href="#page_top"><img src="/img/page_top.gif"></a></p> 