  <div id="footer">
    <div id="footer_contents">
      <div id="footer_title" class="cb">
        <p class="foot_copy"><span>お気軽にご相談ください</span>食生活アドバイザー®</p>
        <p class="tel_btn" x-ms-format-detection="none"><span class="tel_ttl">検定事務局</span><img src="/img/foot_tel.gif" width="29" height="29" alt="tel" />0120-86-3593<br />
        <span class="tel_ttl">Academy事務局</span><img src="/img/foot_tel.gif" width="29" height="29" alt="tel" />0120-20-9039
        <span>受付時間 平日10:00~16:00</span></p>
          <!-- 20250421 外し 指示あり 
          <p id="privacy_mark"><a href="https://privacymark.jp/" target="_blank"><img src="/privacy/img/pmarklogo.gif" width="57" height="61"></a></p>
          -->
          </div>
      <div id="booter_link" class="cb">
        <dl>
          <dt><a href="/">トップページ</a></dt>
          <dt>食生活アドバイザー®とは</dt>
          <dd><a href="/ado/">食生活アドバイザー® ってどんな資格？</a></dd>
          <dd><a href="/ado/field.html">活躍のフィールド</a></dd>
          <dd><a href="/ado/fukugo.html">プラスα複合資格</a></dd>
          <dt>個人受験</dt>
          <dd><a href="/juken/kentei.html">食生活アドバイザー® 検定とは</a></dd>
          
          <!--dd><a href="https://flanet.jp/kobetsu/" target="_blank">個人受験申込方法について</a></dd -->

          <!--dd><a href="/pdf/juken_20250626.pdf" target="_blank">個人受験案内</a></dd-->
          <dd><a href="https://shoku-ad.jp/pdf/jukenguide-new.pdf" target="_blank">個人受験案内</a></dd>
         
          <dd><a href="/juken/">試験概要</a></dd>
          <dd><a href="/juken/kouza.html">合格講座概要</a></dd>
              <dd><a href="/juken/kouza3.html">3級カリキュラム</a></dd>
              <dd><a href="/juken/kouza2.html">2級カリキュラム</a></dd>
          <dd><a href="/juken/mogi3.html">チャレンジ問題</a>
            <ul>
              <li><a href="/juken/mogi3.html">チャレンジ問題3級</a></li>
              <li><a href="/juken/mogi2.html">チャレンジ問題2級</a></li>
            </ul>
          </dd>
          <dd><a href="/juken/mohan.html">検定試験模範解答</a></dd>
          <dd><a href="/pass/">合格講座</a>
            <ul>
              <li><a href="/pass/">速習コース</a></li>
              <li><a href="/pass/education.html">通学コース</a></li>
            </ul>
         </dd>
          <dd><a href="/shoseki/">書籍紹介</a>
            <ul>
              <li><a href="/shoseki/">書籍紹介</a></li>
              <li><a href="/shoseki/past.html">過去問題集</a></li>
            </ul>
         </dd>
          <dd class="btm_border"><a href="/qa/">Q&amp;A（よくある質問）</a></dd>
        </dl>

<!--中央ブロック-->
        <dl>
          <dt>願書請求 </dt>
          <dd><a href="/gansho/">願書請求の流れ</a></dd>

<!--フォームab-->
          <dd><a href="/pdf/20250926_moushikomi.pdf" target="_blank">願書請求フォーム</a></dd>
          <!--dd><a href="https://flanet.jp/application_form/form_b" target="_blank">願書請求フォーム</a></dd-->

          <dd><a href="https://flanet.jp/application_form/form_a" target="_blank">受験申込フォーム</a></dd>
          <!--dd><a href="/pdf/kentei20241225c.pdf" target="_blank">受験申込フォーム</a></dd-->

<!--フォームここまで-->
          <dt><a href="/tusin/">通信講座</a></dt>
          <dd><a href="https://www.hj.sanno.ac.jp/cp/distance-learning/search/?kw=%E9%A3%9F%E7%94%9F%E6%B4%BB%E3%82%A2%E3%83%89%E3%83%90%E3%82%A4%E3%82%B6%E3%83%BC" target="_blank">産業能率大学　総合研究所</a></dd>
          <dd>ユーキャン
      <ul><li><a href="https://www.u-can.co.jp/course/data/in_html/1327/" target="_blank">食生活アドバイザー®合格講座</a></li>
          <li><a href="https://www.u-can.co.jp/course/data/in_html/1400/" target="_blank">野菜スペシャリスト®講座</a><li>
          <li><a href="https://www.u-can.co.jp/course/data/in_html/1545/?il=cooking_1545" target="_blank">作りおき料理コーディネーター®講座</a><li>
      </ul>
         </dd>

          <dd><a href="https://www.jmam.co.jp/tsukyocatalog/category.html" target="_blank">日本能率協会マネジメントセンター</a></dd>

<!--団体受験-->
          <dt>受験（資格関連情報）</dt>
          <dd><a href="/dantai/">団体受験</a></dd>

          <dd><a href="/dantai/pdf/20250926_dantaiannai.pdf" target="_blank">団体受験案内</a></dd>
          <!--dd><a href="https://shoku-ad.jp/pdf/dantai-jukenguide-new.pdf" target="_blank">団体受験案内</a></dd-->

          <dd><a href="https://shoku-ad.jp/pdf/demae-new.pdf" target="_blank">出前講座</a></dd>
          <!--dd><a href="/dantai/pdf/demae53.pdf" target="_blank">出前講座</a></dd-->

<!--団体受験フォーム-->
          <dd><a href="/dantai/pdf/20250926_dantaimoushikomi.pdf" target="_blank">団体受験お申込み</a></dd>
          <!--dd><a href="https://flanet.jp/dantai_form/" target="_blank">団体受験お申込み</a></dd-->

          <dd><a href="/gokaku/">合格者の声 </a>　　
            <ul>
              <li><a href="/gokaku/">M.Sさん</a></li>
              <li><a href="/gokaku/index2.html">H.Nさん</a></li>
            </ul>
          </dd>
          <dd class="btm_border"><a href="https://shoku-ad.jp/member/" target="_blanck">食アド<sub>®</sub> 会員制度</a></dd>
<!--
          <dd class="btm_border"><a href="/kaiin/">食アド<sub>®</sub> 会員制度</a></dd>
          <dt>日本の資格検定</dt>
          <dd class="btm_border"><a href="https://jpsk.jp/article/award2019.html" target="_blank">「日本の資格・検定」AWARDS 2019</a></dd>
-->
        </dl>

<!--右ブロック-->
        <dl class="no_dl">
          <dt><a href="/kyokai/">協会情報</a></dt>
          <dd><a href="/kyokai/">会長のごあいさつ</a></dd>
          <dd><a href="/kyokai/index2.html">FLAネットワーク®協会とは</a></dd>

          <dt>OTHERS</dt>
          <dd><a href="/info/">お問い合せ</a></dd>
          <dd><a href="/link/">リンク集</a></dd>
          <dd><a href="/sitemap/">サイトマップ</a></dd>

          <dt>食生活アドバイザー® のための健康レシピ</dt>
					<dd><a href="/recipe/">レシピ一覧</a></dd>

<!--20230105up時から非表示
          <dt>月刊コラム 食生活マメ知識</dt>
          <dd><a href="/column/">更新月順一覧</a></dd>
          <dd><a href="/column/index2.html">カテゴリ別一覧</a></dd>
-->
          <dt>食アド<sub>®</sub> &  野スぺ<sub>®</sub></dt>
					<dd><a href="https://shoku-ad.jp/club2022/newstable/">月刊ニューステーブル</a></dd>
          <dt><a href="/privacy/index2.html">個人情報</a></dt>
          <dd><a href="/privacy/index2.html">個人情報保護方針</a></dd>

<!-- 20250421 トル指示 
          <dd><a href="/privacy/index3.html">個人情報の利用目的の公表、<br />及び開示等に応じる手続き</a></dd>
-->
          <dt class="btm_border"><a href="https://flanet.jp/torihikihou/index.html">特定商取引に基づく表記</a></dt>

<!--最初は class="btm_border" が一つ上の個人情報の利用目的の公表の<dd>の中にあってこれが閉じ線になっている-->

        </dl>
      </div>

    </div>
    <p id="footer_copy">Copyright(C) 2019 FLAネットワーク®協会 All Rights Reserved</p>
  </div>
  <p id="pagetop"><a href="#page_top"><img src="/img/page_top.gif" width="56" height="56" alt="ページの先頭へ" class="btnover" /></a></p>  
