
<!--side_banner start -->
<ul id="side_banner">





<!--個人受験-->

<!--li id="side_banner25"><a href="https://flanet.jp/kobetsu/" target="_blank"><img src="/img/side_banner25.gif" alt="個人受験申込方法について" class="btnover" /></a></li-->

<!--li id="side_banner01"><a href="/pdf/20251006_moushikomi.pdf" target="_blank"><img src="../img/side_banner01.gif" alt="願書請求フォーム" class="btnover" /></a></li-->
<!--li id="side_banner01"><a href="https://flanet.jp/application_form/form_b" target="_blank"><img src="/img/side_banner01.gif" alt="願書請求フォーム" class="btnover" /></a></li-->

<!--li id="side_banner02"><a href="https://flanet.jp/application_form/form_a" target="_blank"><img src="/img/side_banner02.gif" alt="受験申込フォーム" class="btnover" /></a></li-->
<!--li id="side_banner02"><a href="/pdf/kentei20241225c.pdf" target="_blank"><img src="/img/side_banner02.gif" alt="受験申込フォーム" class="btnover" /></a></li-->

<!--li id="side_banner26"><a href="https://shoku-ad.jp/pdf/jukenguide-new.pdf" target="_blank"><img src="/img/side_banner26.gif" alt="個人受験案内" class="btnover" /></a></li-->
<!--li id="side_banner26"><a href="https://shoku-ad.jp/pdf/annai53.pdf" target="_blank"><img src="/img/side_banner26.gif" alt="個人受験案内" class="btnover" /></a></li-->


<li id="side_banner23"><a href="/juken/" target="_blank"><img src="/img/person_examination_min.png" ait="個人受験" class="btnover" /></a></li>






<!--個人受験ここまで-->

<!--団体受験-->
<li id="side_banner24"><a href="/dantai/" target="_blank"><img src="/img/grop_examination_min.png" ait="団体受験" class="btnover" /></a></li>

<li id="side_banner25"><a href="/dantai/pdf/20250926_dantaimoushikomi.pdf" target="_blank"><img src="/img/side_banner23.jpg" ait="団体受験申込フォーム" class="btnover" /></a></li>
<!--li id="side_banner25"><a href="https://flanet.jp/dantai_form/" target="_blank"><img src="/img/side_banner23.jpg" ait="団体受験申込フォーム" class="btnover" /></a></li-->

<!--食アド® アカデミー-->
<li id="side_banner27"><a href="https://shoku-ad.jp"><img src="/img/side_banner24.jpg" ait="食アド® アカデミー" class="btnover" /></a></li>


<li id="side_banner17"><a href="https://www.hj.sanno.ac.jp/cp/distance-learning/search/?kw=%E9%A3%9F%E7%94%9F%E6%B4%BB%E3%82%A2%E3%83%89%E3%83%90%E3%82%A4%E3%82%B6%E3%83%BC" target="_blank"><img src="/img/side_banner16.gif" alt="産能大通信講座" class="btnover" /></a></li>
<li id="side_banner07"><a href="/pass/index.html"><img src="/img/side_banner07.jpg" alt="合格を目指して集中的に学習しよう 合格講座" class="btnover" /></a></li>
<li><a href="/shoseki/"><img src="/img/side_banner09.gif" alt="書籍紹介" class="btnover" /></a></li>
<li id="side_banner21"><a href="/shoseki/past.html#moushikomi"><img src="/img/side_banner21.jpg" alt="過去問題集" class="btnover" /></a></li>
<li id="side_banner22"><a href="/ado/"><img src="/img/side_banner22.jpg" alt="食生活アドバイザー®とは" class="btnover" /></a></li>
<li id="side_banner05"><a href="/gansho/"><img src="/img/side_banner05.jpg" alt="受験までの流れをチェック 願書請求について" class="btnover" /></a></li>
<li id="side_banner18" class="m_b10"><a href="/gokaku/"><img src="/img/side_banner11.jpg" alt="合格者の声 　S.Hさん／S.Sさん" class="btnover" /></a></li>
<li id="side_banner09" class="m_b25"><a href="/gokaku/index2.html"><img src="/img/side_banner12.jpg" alt="合格者の声 　H.Aさん／M.Aさん" class="btnover" /></a></li>
<li class="m_b10" id="syoseki_banner">
<p><a target="_blanck" href="https://shoku-ad.jp/member/"><img src="/img/side_banner10.gif" alt="食アド会員制度" class="btnover" /></a></p>
</li>
<li class="m_b10" id="koramu_banner">
<!--20230105UP時より非表示
<p class="m_b10"><a href="/column/"><img src="/img/side_banner13.gif" alt="月刊コラム 食生活マメ知識" class="btnover" /></a></p>
-->
<p id="side_health_recipes"><a href="/recipe/"><img src="/img/side_banner14.gif" alt="食生活アドバイザー®のための健康レシピ" class="btnover" /></a></p>
</li>
<!--ユーキャン-->
<li id="side_banner03"><a href="http://www.u-can.co.jp/course/data/in_html/1327/" target="_blank"><img src="/img/side_banner03.jpg" alt="ユーキャンの食生活アドバイザー（2級・3級）" class="btnover" /></a></li>
<li id="side_banner08"><a href="http://www.u-can.co.jp/course/data/in_html/1400/" target="_blank" class="btnover"></a></li>
<!--JMAM-->
<li id="side_banner20"><a href="https://www.jmam.co.jp/tsukyocatalog/category.html" target="_blank"><img src="/img/side_banner18.gif" alt="JMAM" class="btnover" /></a></li>

</ul>
<!--side_banner end --> 

<!--top_bottom_link start -->
<ul id="top_bottom_link" class="cb">
<li id="top_kyokai"><a href="/kyokai/"><img src="/img/btn_link_arrow.png" />協会情報</a></li>
<li id="top_tusin"><a href="/tusin/"><img src="/img/btn_link_arrow.png" />通信講座</a></li>
<li id="top_link"><a href="/link/"><img src="/img/btn_link_arrow.png" />リンク集</a></li>
</ul>
<!--top_bottom_link end --> 